pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-kube-gen-s3events-triggerlambda
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    dockerfile: app/Dockerfile
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
    when:
      branch: build/*

  run-gen-s3events-trigger-test:
    image: quay.io/ukhomeofficedigital/dq-kube-gen-s3events-triggerlambda:5
    environment:
      - S3_BUCKET=s3-dq-api-cdlz-msk-test
      - LAMBDA_FUNC=arn:aws:lambda:eu-west-2:797728447925:function:api-kafka-input-test-trigger
      - LAST_MOD_DTTIME_START=2020-07-09 10:55:31
      - LAST_MOD_DTTIME_END=2020-07-09 10:55:31
      - S3_PREFIX=parsed
      - S3_SUFFIX=jsonl
      - WAIT_SEC=60
    commands:
      - export AWS_ACCESS_KEY_ID=$$TEST_AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$$TEST_AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$$AWS_DEFAULT_REGION
      - python app/scripts/gen_events_trigger_lambda.py
    secrets:
      - TEST_AWS_ACCESS_KEY_ID
      - TEST_AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    when:
      branch: test/*

  run-gen-s3events-trigger-notprod:
    image: quay.io/ukhomeofficedigital/dq-kube-gen-s3events-triggerlambda:5
    environment:
      - S3_BUCKET=s3-dq-api-cdlz-msk-notprod
      - LAMBDA_FUNC=arn:aws:lambda:eu-west-2:797728447925:function:api-kafka-input-notprod-trigger
      - LAST_MOD_DTTIME_START=2020-07-09 10:55:31
      - LAST_MOD_DTTIME_END=2020-07-09 10:55:31
      - S3_PREFIX=parsed
      - S3_SUFFIX=jsonl
      - WAIT_SEC=60
    commands:
      - export AWS_ACCESS_KEY_ID=$$NOTPROD_AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$$NOTPROD_AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$$AWS_DEFAULT_REGION
      - python app/scripts/gen_events_trigger_lambda.py
    secrets:
      - NOTPROD_AWS_ACCESS_KEY_ID
      - NOTPROD_AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    when:
      branch: notprod/*

  run-gen-s3events-trigger-prod:
    image: quay.io/ukhomeofficedigital/dq-kube-gen-s3events-triggerlambda:5
    environment:
      - S3_BUCKET=s3-dq-api-cdlz-msk-prod
      - LAMBDA_FUNC=arn:aws:lambda:eu-west-2:797728447925:function:api-kafka-input-notprod-trigger
      - LAST_MOD_DTTIME_START=2020-07-09 10:55:31
      - LAST_MOD_DTTIME_END=2020-07-09 10:55:31
      - S3_PREFIX=parsed
      - S3_SUFFIX=jsonl
      - WAIT_SEC=60
    commands:
      - export AWS_ACCESS_KEY_ID=$$PROD_AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$$PROD_AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$$AWS_DEFAULT_REGION
      - python app/scripts/gen_events_trigger_lambda.py
    secrets:
      - PROD_AWS_ACCESS_KEY_ID
      - PROD_AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGIONs
    when:
      branch: prod/*
