---
apiVersion: v1
kind: Secret
metadata:
  name: dq-athena-partition-maintenance
type: Opaque
data:
  S3_BUCKET: {{.S3_BUCKET}}
  LAMBDA_FUNC: {{.LAMBDA_FUNC}}
  AWS_ACCESS_KEY_ID: {{.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: {{.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: {{.AWS_DEFAULT_REGION}}
